import { useCallback, useEffect, useMemo, useState } from 'react';
import { CalendarCheck2, FileText, HeartPulse, MessageSquare, Plus } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import PatientLayout from '../../layouts/PatientLayout';
import Card from '../../components/ui/Card';
import StatCard from '../../components/ui/StatCard';
import Button from '../../components/ui/Button';
import Spinner from '../../components/ui/Spinner';
import ErrorBanner from '../../components/shared/ErrorBanner';
import EmptyState from '../../components/shared/EmptyState';
import RiskBadge from '../../components/patient/RiskBadge';
import ReportSummaryCard from '../../components/patient/ReportSummaryCard';
import apiClient from '../../api/apiClient';

export default function PatientDashboardPage() {
  const navigate = useNavigate();
  const [overview, setOverview] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState('');

  const fetchDashboard = useCallback(async () => {
    setIsLoading(true);
    setError('');
    try {
      const response = await apiClient.get('/patient/dashboard');
      setOverview(response.data);
    } catch (err) {
      setError(err?.response?.data?.message || 'Unable to load your dashboard right now.');
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchDashboard();
  }, [fetchDashboard]);

  const statCards = useMemo(
    () => [
      { label: 'Completed Checkups', value: overview?.totalReports || 0, icon: FileText },
      {
        label: 'Latest Risk',
        value: overview?.latestReport?.riskLevel
          ? overview.latestReport.riskLevel.charAt(0).toUpperCase() +
            overview.latestReport.riskLevel.slice(1)
          : 'N/A',
        icon: HeartPulse,
      },
      {
        label: 'Last Checkup',
        value: overview?.latestReport?.createdAt
          ? new Date(overview.latestReport.createdAt).toLocaleDateString()
          : 'Not yet',
        icon: CalendarCheck2,
      },
    ],
    [overview],
  );

  return (
    <PatientLayout
      title="Patient Console"
      subtitle="Track your latest assessments and care tips."
      actions={
        <Button onClick={() => navigate('/app/checkup/new')}>
          <Plus className="mr-2 h-4 w-4" />
          New AI Checkup
        </Button>
      }
    >
      {error && (
        <div className="mb-6 space-y-3">
          <ErrorBanner message={error} />
          <Button variant="outline" size="sm" onClick={fetchDashboard}>
            Retry
          </Button>
        </div>
      )}

      {isLoading ? (
        <div className="flex min-h-[280px] items-center justify-center">
          <Spinner className="h-8 w-8 border-slate-300" />
        </div>
      ) : (
        <>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {statCards.map((stat) => (
              <StatCard key={stat.label} {...stat} />
            ))}
          </div>

          <div className="mt-8 grid gap-6 lg:grid-cols-2">
            <Card>
              <div className="flex items-center justify-between">
                <h3 className="text-lg font-semibold text-slate-900">Most recent report</h3>
                {overview?.latestReport && (
                  <RiskBadge level={overview.latestReport.riskLevel} className="text-xs" />
                )}
              </div>
              {overview?.latestReport ? (
                <>
                  <p className="mt-2 text-sm text-slate-500">
                    Generated on{' '}
                    {new Date(overview.latestReport.createdAt).toLocaleDateString(undefined, {
                      month: 'long',
                      day: 'numeric',
                      year: 'numeric',
                    })}
                  </p>
                  <p className="mt-4 text-sm text-slate-600">{overview.latestReport.summary}</p>
                  <div className="mt-4 flex justify-end">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => navigate(`/app/reports/${overview.latestReport._id}`)}
                    >
                      View full report
                    </Button>
                  </div>
                </>
              ) : (
                <EmptyState
                  title="No reports yet"
                  description="Once you complete an AI checkup, your summary will appear here."
                  className="mt-4 bg-white"
                />
              )}
            </Card>

            <Card>
              <h3 className="text-lg font-semibold text-slate-900">Care guidance</h3>
              <p className="mt-2 text-sm text-slate-500">
                Personalized tips generated by the assistant will surface after each checkup.
              </p>
              <div className="mt-4 rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">
                <MessageSquare className="mb-2 h-4 w-4 text-blue-500" />
                Stay hydrated, note any changes to your primary symptoms, and contact your care team
                if your condition escalates.
              </div>
            </Card>
          </div>

          {overview?.latestReport && (
            <div className="mt-8">
              <ReportSummaryCard report={overview.latestReport} />
            </div>
          )}
        </>
      )}
    </PatientLayout>
  );
}

